version: 2
jobs:
  build:

    macos:
      xcode: "10.0.0"

    steps:
      - checkout

      # Build the app and run tests
      - run:
          name: Build and run tests
          command: .circleci/test.sh
